services:
  - type: web
    name: lycee-backend
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: sh ./start.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: lycee_moxs
      - key: DB_USER
        value: lycee_moxs_user
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: dpg-db2h01c9v7es73c4t0sg-a
      - key: DB_PORT
        value: "5432"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: FRONTEND_URL
        value: https://lyceemidongysud.vercel.app
      - key: SEED_DEMO_DATA
        value: "true"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: noreply@lyceemidongysud.mg
      - key: SUPERUSER_EMAIL
        value: admin@gmail.com
      - key: SUPERUSER_PASSWORD
        value: "123456"
      - key: SUPERUSER_FIRST_NAME
        value: Admin
      - key: SUPERUSER_LAST_NAME
        value: Portal
      - key: SUPERUSER_MATRICULE
        value: ADM-ROOT-001
