services:
  - type: web
    name: lycee-backend
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: gunicorn lycee.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: lycee_moxs
      - key: DB_USER
        value: lycee_moxs_user
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: dpg-db2h01c9v7es73c4t0sg-a
      - key: DB_PORT
        value: "5432"
      - key: ALLOWED_HOSTS
        value: .onrender.com
