# Generated by Django 5.2.14 on 2026-09-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_classe_academic_year_classe_stream'),
        ('matieres', '0003_matiere_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='classes.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='matieres.matiere')),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR', 'status': 'ACTIVE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_hour'],
                'unique_together': {('classe', 'matiere', 'professeur', 'day_of_week', 'start_hour', 'academic_year')},
            },
        ),
    ]
