# Generated by Django 5.2.14 on 2026-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weight_note_1', models.DecimalField(decimal_places=2, default=0.3, help_text='Weight of first score (e.g., 0.3 = 30%)', max_digits=3)),
                ('weight_note_2', models.DecimalField(decimal_places=2, default=0.7, help_text='Weight of second score (e.g., 0.7 = 70%)', max_digits=3)),
                ('is_locked', models.BooleanField(default=False, help_text="If True, grades can't be modified without justification")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
