# Generated by Django 5.2.14 on 2026-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_add_examperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Coefficient de la matière (utilisé pour le calcul des moyennes)'),
        ),
    ]
