# Generated by Django 5.2.14 on 2026-09-01 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_absence', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('LATE', 'En retard'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('motif', models.TextField(blank=True)),
                ('justifiee', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Server timestamp when the pointage was recorded', null=True)),
                ('sync_source', models.CharField(choices=[('ONLINE', 'En ligne'), ('OFFLINE_SYNCED', 'Synchronisé hors-ligne')], default='ONLINE', max_length=20)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for offline deduplication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_absence', '-created_at'],
            },
        ),
    ]
