# Generated by Django 5.2.14 on 2026-09-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='etudiants.etudiant'),
        ),
    ]
