# Generated by Django 5.2.14 on 2026-09-04 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0003_enrollment_devise_enrollment_frais_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('REVENUE', 'Recette'), ('EXPENSE', 'Dépense')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System categories cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie budgétaire',
                'verbose_name_plural': 'Catégories budgétaires',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bilan budgétaire',
                'verbose_name_plural': 'Bilans budgétaires',
            },
        ),
        migrations.CreateModel(
            name='BudgetReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel (3 derniers mois)'), ('YEARLY', 'Annuel (année scolaire)')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('GENERATING', 'Génération en cours'), ('READY', 'Prêt'), ('FAILED', 'Échec')], default='GENERATING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='budget/reports/')),
                ('data_json', models.JSONField(blank=True, help_text='Données du rapport pour affichage web', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport budgétaire',
                'verbose_name_plural': 'Rapports budgétaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('REVENUE', 'Recette'), ('EXPENSE', 'Dépense')], max_length=10)),
                ('academic_year', models.CharField(help_text='Format: YYYY-YYYY (ex: 2024-2025)', max_length=9)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, help_text='Désignation pour subventions/dons', max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='Numéro de pièce justificative', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='budget/')),
                ('revenue_source', models.CharField(blank=True, choices=[('TUITION', 'Scolarité élève'), ('SUBSIDY', 'Subvention'), ('DONATION', 'Don'), ('OTHER_REVENUE', 'Autre recette')], max_length=20, null=True)),
                ('expense_type', models.CharField(blank=True, choices=[('CLEANING', 'Matériel ménage'), ('OFFICE_SUPPLIES', 'Fournitures bureau (stylos, papier)'), ('TEACHER_NON_PERM', 'Paiement enseignants non-fonctionnaires'), ('SURVEILLANT', 'Paiement surveillants'), ('GUARD', 'Paiement gardiens'), ('SPORTS_EQUIPMENT', 'Matériel sportif'), ('MAINTENANCE', 'Maintenance/réparations'), ('UTILITIES', 'Eau/électricité/internet'), ('OTHER_EXPENSE', 'Autre dépense')], max_length=20, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='budget.budgetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items_created', to=settings.AUTH_USER_MODEL)),
                ('related_enrollment', models.ForeignKey(blank=True, help_text="Lien automatique avec l'inscription pour les paiements de scolarité", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='etudiants.enrollment')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['academic_year', 'item_type', 'date'], name='budget_budg_academi_104924_idx'), models.Index(fields=['category', 'item_type'], name='budget_budg_categor_141695_idx')],
            },
        ),
    ]
