# Generated by Django 5.2.14 on 2026-09-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('classes', '0003_room_schoolconfig_matierecoefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='related_teacher_assignment',
            field=models.ForeignKey(blank=True, help_text="Lien avec l'affectation enseignante pour les salaires", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='classes.teacherassignment'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='devise',
            field=models.CharField(default='MGA', max_length=3),
        ),
    ]
