# Generated by Django 5.2.14 on 2026-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('SECONDAIRE_GENERAL', 'Secondaire Général'), ('SECONDAIRE_TECHNIQUE', 'Secondaire Technique'), ('PRIMAIRE', 'Primaire')], max_length=30)),
                ('capacite', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['niveau', 'nom'],
            },
        ),
    ]
