# Generated by Django 5.2.14 on 2026-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Format: YYYY-YYYY (ex: 2024-2025)', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='stream',
            field=models.CharField(blank=True, choices=[('S', 'Scientifique (S)'), ('L', 'Littéraire (L)'), ('OSE', 'Socio-Économique (OSE)'), ('TC', 'Technique Commercial'), ('TI', 'Technique Industriel'), ('G', 'Générale')], help_text='Filière/Stream (S, L, OSE, etc.) - null for général', max_length=5, null=True),
        ),
    ]
