# Generated by Django 5.2.14 on 2026-09-03 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_academic_year_classe_stream'),
        ('matieres', '0003_matiere_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveIntegerField(default=30)),
                ('batiment', models.CharField(blank=True, max_length=50)),
                ('equipement', models.TextField(blank=True, help_text='Projecteur, tableau, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, unique=True)),
                ('school_name', models.CharField(default='Lycée Horizon', max_length=200)),
                ('school_address', models.CharField(blank=True, max_length=300)),
                ('school_phone', models.CharField(blank=True, max_length=30)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('frais_inscription_defaut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ecolage_annuel_defaut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tolerance_retard_minutes', models.PositiveIntegerField(default=10)),
                ('heure_debut_cours', models.TimeField(blank=True, null=True)),
                ('heure_fin_cours', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', '-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='MatiereCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('SECONDAIRE_GENERAL', 'Secondaire Général'), ('SECONDAIRE_TECHNIQUE', 'Secondaire Technique'), ('PRIMAIRE', 'Primaire')], help_text="Niveau où ce coefficient s'applique", max_length=30)),
                ('stream', models.CharField(blank=True, choices=[('S', 'Scientifique (S)'), ('L', 'Littéraire (L)'), ('OSE', 'Socio-Économique (OSE)'), ('TC', 'Technique Commercial'), ('TI', 'Technique Industriel'), ('G', 'Générale')], help_text='Filière spécifique (optionnel)', max_length=5, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='matieres.matiere')),
            ],
            options={
                'ordering': ['matiere', 'niveau', 'stream'],
                'unique_together': {('matiere', 'niveau', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('is_main_teacher', models.BooleanField(default=False, help_text='Professeur principal de la classe (accès à toutes les matières pour cette classe)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='matieres.matiere')),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR', 'status': 'ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classe', 'matiere', 'professeur'],
                'unique_together': {('professeur', 'classe', 'matiere', 'academic_year')},
            },
        ),
    ]
