# Generated by Django 5.2.14 on 2026-10-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_room_schoolconfig_matierecoefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='coverage_reason',
            field=models.CharField(blank=True, default='', help_text='Raison du remplacement (ex. manque de prof, congé, activité de remplacement)', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='is_substitute',
            field=models.BooleanField(default=False, help_text='Affectation de remplacement ou d’aide pour couvrir une matière tant qu’un prof titulaire manque.'),
        ),
    ]
