# Generated by Django 5.2.14 on 2026-09-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.DecimalField(decimal_places=2, default=0, help_text='Première note (ex: Interrogation)', max_digits=4)),
                ('score_2', models.DecimalField(blank=True, decimal_places=2, help_text='Deuxième note (ex: Devoir de Synthèse)', max_digits=4, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_evaluation', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('LOCKED', 'Verrouillé')], default='DRAFT', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('exam_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='matieres.examperiod')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matieres.matiere')),
            ],
            options={
                'ordering': ['-date_evaluation', 'etudiant'],
            },
        ),
    ]
