# Generated by Django 5.2.14 on 2026-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Validé'), ('REJECTED', 'À corriger'), ('LOCKED', 'Verrouillé')], default='DRAFT', max_length=10),
        ),
    ]
