# Generated by Django 5.2.14 on 2026-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surveillant_type',
            field=models.CharField(blank=True, choices=[('GENERAL', 'Surveillant général'), ('ETAGE', "Surveillant d'étage"), ('PORTE', 'Surveillant de porte'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PROFESSEUR', 'Professeur'), ('ELEVE', 'Élève'), ('PARENT', 'Parent'), ('SURVEILLANT', 'Surveillant')], max_length=20),
        ),
    ]
