# Generated by Django 5.2.14 on 2026-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_surveillant_type_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire de base pour les enseignants non-fonctionnaires (SUPPLEANT)', max_digits=12, null=True),
        ),
    ]
