# Generated by Django 5.2.14 on 2026-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_secretariat_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du titulaire de compte pour l’affichage du badge', null=True, upload_to='photos/users/'),
        ),
    ]
