# Generated by Django 5.2.14 on 2026-09-01 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text="Type d'entité (Grade, Enrollment, Attendance, etc.)", max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('STATUS_CHANGE', 'Changement de statut')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Justification for the action (e.g., correction)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Format: YYYY-YYYY (ex: 2024-2025)', max_length=9)),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Payé'), ('PARTIAL', 'Partiel'), ('UNPAID', 'Non payé')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('PUSH', 'Push notification'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('notification_type', models.CharField(help_text='Type de notification (ABSENCE, NOTE, PAYMENT, etc.)', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, help_text='Additional data for the notification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentOrientation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_stream', models.CharField(choices=[('S', 'Scientifique (1ère S)'), ('L', 'Littéraire (1ère L)'), ('OSE', 'Socio-Économique (1ère OSE)')], max_length=5)),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, help_text='Percentage score (0-100)', max_digits=5)),
                ('ai_explanation', models.TextField(blank=True, help_text='Human-readable explanation of the recommendation')),
                ('ai_model_version', models.CharField(help_text='Version of the AI model used for this prediction', max_length=50)),
                ('final_stream', models.CharField(blank=True, choices=[('S', 'Scientifique (1ère S)'), ('L', 'Littéraire (1ère L)'), ('OSE', 'Socio-Économique (1ère OSE)')], max_length=5, null=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'student'],
            },
        ),
    ]
