# Generated by Django 5.2.14 on 2026-09-01 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ELEVE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='etudiants.etudiant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentorientation',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed/rejected the recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientations_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentorientation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientations', to='etudiants.etudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
