# Generated by Django 5.2.14 on 2026-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='devise',
            field=models.CharField(default='XOF', help_text='Devise des paiements', max_length=3),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='frais_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais total d'inscription", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='frais_verses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant versé', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Fichier PDF du reçu de paiement', null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('APPLICANT', 'Candidat'), ('ENROLLED', 'Inscrit'), ('SUSPENDED', 'Suspendu'), ('GRADUATED', 'Diplômé')], default='ENROLLED', max_length=20),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
