# Generated by Django 5.2.14 on 2026-10-06 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_notification_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOfficePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CONVOCATION', 'Convocation'), ('ENTRY', 'Billet d’entrée'), ('RETURN', 'Autorisation de retour en classe')], max_length=20)),
                ('reason', models.TextField()),
                ('destination', models.CharField(default='Vie scolaire', max_length=120)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'En attente'), ('USED', 'Utilisé'), ('CANCELLED', 'Annulé')], default='OPEN', max_length=12)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_office_passes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_passes', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
