# Generated by Django 5.2.14 on 2026-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_studentofficepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de l’élève pour l’affichage du badge', null=True, upload_to='photos/etudiants/'),
        ),
    ]
